### PR TITLE
Replace stream with readable-stream

### PR DESCRIPTION
**Pull request by byterose**
#21

### CODE REVIEW

**Comment by samuveth** [comment]
Very much needed for Vite!

**Comment by dievardump** [comment]
Could we have this merged so people not using webpack can use the library?

**Comment by fanatid** [comment]
1. `readable-stream` should be added to `package.json`
2. Is it possible to solve `webpack` issue with `resolve.fallback`? https://github.com/cryptocoinjs/keccak/issues/21#issuecomment-874092461

**Comment by sirius651** [comment]
```
Is it possible to solve webpack issue with resolve.fallback? 
```
I tried to adding fallback, but it's not work. maybe above PR can work

**Comment by byterose** [comment]
> @byterose thank you for PR, two questions:
> 
> 1. `readable-stream` should be added to `package.json`
> 2. Is it possible to solve `webpack` issue with `resolve.fallback`? [Transform not found? #21 (comment)](https://github.com/cryptocoinjs/keccak/issues/21#issuecomment-874092461)

1. I just pushed a commit to add `readable-stream` to `package.json` 🙂
2. I tried to do this before I created this pr, but it didn't seem to work

**Comment by fanatid** [comment]
Thanks! Published as `3.0.2`.

**Pull request merged**
