### PR TITLE
Allow Uint8Array inputs

### PR DESCRIPTION
**Pull request by jacogr**
Allow Uint8Array as input values as well, these can be iterated in the same way inside `absorb` (or `update`) as the `Buffer`.

### CODE REVIEW

**Comment by dcousens** [comment]
What situation are you in where `Buffer` is not equal to `Uint8Array`?

**Comment by fanatid** [comment]
@jacogr are you want fix all libraries which you are using? https://github.com/ethereumjs/rlp/pull/16
Why not convert Uint8Array to Buffer before pass it?

**Comment by fanatid** [comment]
From other side, [Hash#update](https://nodejs.org/api/crypto.html#crypto_hash_update_data_inputencoding) allow not only `string`/`Buffer`. Maybe we should change crypto-browserify libraries... @dcousens ?

**Comment by jacogr** [comment]
The conversion between Uint8Array -> Buffer is a simple one, i.e. `Buffer.from(u8a)`. However by skipping this (underlying inside the library the iteration of the data stays the same), it minimises the unneeded allocations that does happen when your are dealing mostly with `Uint8Array` (my specific case), i.e. no `keccack(Buffer.from(data))` where I'm calling.

So yes, Buffer === Uint8Array (mostly), however Uint8Array !== Buffer (when passed in, needs a conversion). 

Additionally, you are correct though, if we are attempting to strictly match Hash#update, the API is a bit wider than currently implemented. (And my PR falls short of expanding that completely)

**Pull request closed without merging**
